### ISSUE TITLE
Lots of inconsistencies in specification

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/flipt-openapi#25]
It was brought to my attention in Discord that this specification in broken here:
https://github.com/flipt-io/flipt-openapi/blob/main/openapi.yml#L492

This is referencing a type that does not exist.
However, looking a little closer, we haven't documented the new evaluation API either. Im wondering what else might be broken in this spec too. We should review it ASAP.

**Comment by erka** [comment]
@markphelps @GeorgeMac is there any reason why we can't use `buf.build/community/google-gnostic-openapi` to generate this spec for us?

**Comment by markphelps** [comment]
@erka we could definitely try it and see how closely the generated openAPI spec matches our current one!

**Comment by erka** [comment]
@markphelps I give it  a try https://github.com/erka/flipt/pull/19/files.

**Comment by markphelps** [comment]
> @markphelps I give it a try https://github.com/erka/flipt/pull/19/files.

whoa this looks great! gonna do a quick comparison of the generated openapi yml and our handcoded one

**Comment by erka** [comment]
One thing is the naming of components. As an example, `ConstraintCreateRequest` goes into `CreateConstraintRequest`

**Comment by markphelps** [comment]
@erka I think thats ok

**Comment by GeorgeMac** [comment]
Thats awesome @erka I haven't seen that generator before!

**Comment by GeorgeMac** [comment]
Hey @erka 👋 That PR looks pretty great, want to get it based on Flipt?
I know there are some folks that would love to get Metadata in.

**Comment by erka** [comment]
@GeorgeMac I really would like to do it but there are some things what I dislike. One of them is `go.sum` with crazy references to many versions of `cloud.google.com/go`. I don't want to add 1k+ lines there. How can I fix that problem?

**Comment by markphelps** [comment]
@erka we could try deleting `go.sum` and regenerating (`go mod tidy`) sometimes that helps prune extra dependencies that arent actually needed. same with `go.work.sum`

**Comment by erka** [comment]
It looks like people use import `"github.com/google/gnostic-models/openapiv3"` as a replacement for `"github.com/google/gnostic/openapiv3"`. And it solves the dependencies issue but I can do only manual right now.

**Comment by GeorgeMac** [comment]
Cheers @erka I will check it tomorow AM! Appreciate you taking a stab at that.

**Comment by markphelps** [comment]
Closing since https://github.com/flipt-io/flipt/pull/3357 was added

Thanks again @erka !!
